# Generated by Django 4.0.5 on 2022-06-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_remove_departamento_numerocuartos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='numeroCuartos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
